### ISSUE TITLE
Using suchThat makes test to never halt

### ISSUE THREAD

**Issue by anttih** [purescript-contrib/purescript-strongcheck#17]
```
suchThat (chooseInt (-99.0) 99.0) (/= 0)
```

It seems that once the predicate returns false, it won't generate anything anymore and the tests stop. Using `(const true)` there makes the tests run normally.

**Comment by anttih** [comment]
Here's a failing test: https://github.com/anttih/purescript-strongcheck/blob/such-that-bug/test/Test/Main.purs#L95

This only happens when trying to generate one value out of the generator. If I change that to 

```
suchThat'   <- collectAll mempty $ suchThat (chooseInt 0.0 4.0) (/= 2)
```

it works as expected.

**Comment by garyb** [comment]
I see another problem here too, why does `chooseInt` accept `Number`s? :wink:

**Comment by beckyconning** [comment]
:+1: i'm also having this issue.

**Comment by beckyconning** [comment]
In the Haskell QuickCheck `suchThat` `resize`s the the `Gen` when the predicate isn't affirmed.

https://hackage.haskell.org/package/QuickCheck-2.8.1/docs/src/Test-QuickCheck-Gen.html#suchThat

**Comment by jdegoes** [comment]
> I see another problem here too, why does chooseInt accept Numbers? :wink:

Because *someone* submitted the `Int` cleanup to quickcheck but not strongcheck. Not pointing any fingers, mind you. :wink:

**Comment by beckyconning** [comment]
https://github.com/purescript-contrib/purescript-strongcheck/pull/18
