### ISSUE TITLE
Wrap `check` in `try`

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-strongcheck#47]
If you have some error in property and it throws then you will lose seed number.

Would be nice to wrap `check` in try and if there is error log seed number and re-throw the error 

https://github.com/purescript-contrib/purescript-strongcheck/blob/master/src/Test/StrongCheck.purs#L169-L173

**Comment by garyb** [comment]
It's kinda bad to do this since it goes against the expectation that non-Eff code is going to be pure, but on the other hand this is a testing library so being able to reproduce bugs would be a good thing.
