### ISSUE TITLE
not compiling with purescript 0.12

### ISSUE THREAD

**Issue by CarstenKoenig** [purescript-contrib/purescript-strongcheck#51]
I did not check it directly against the lib yet, but if I let bower download this (it happened to me while testing `purescript-agonaut-codecs` which tests have a dependency to `purescript-strongcheck`), I get an error like this:

```
Compiling Test.StrongCheck
Error found:
in module Test.StrongCheck
at bower_components\purescript-strongcheck\src\Test\StrongCheck.purs line 80, column 10 - line 80, column 24

  Could not match type

    Lazy

  with type

    Function Unit


while trying to match type Free Lazy
  with type Free (Function Unit)
while checking that expression (flip bind) test
  has type GenT (Free Lazy) prop0 -> GenT (Free (Function Unit)) Result
in value declaration testableGen

where prop0 is a rigid type variable

See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
or to contribute content related to this error.
```

here is the "offending" line:

https://github.com/purescript-contrib/purescript-strongcheck/blob/10ab003a77f87711e51cd74e954c9bcb4691d93f/src/Test/StrongCheck.purs#L80

**Comment by garyb** [comment]
If you're working on updating strongcheck just because some library depends on it, I'd recommend switching it to quickcheck instead, unless it truly is using some strongcheck specific feature.

**Comment by CarstenKoenig** [comment]
@garyb do you want to drop *Strongcheck*?

I don't want to change anything - I just want to report, that right now as far as I can see this library does not compile with *purs 0.12* against it's dependencies.

Yes ultimately it's because I need that other library but even that is just a transient dependency of mine.

I'm in no position to change any dependency of those libraries - I'm just trying to help out, because I want to use *PureScript* and give something back.

Sorry if the way I reported this problem or anything else was offending.

**Comment by newlandsvalley** [comment]
Me too - I'm waiting for `purescript-rationals` which depends on it.

**Comment by garyb** [comment]
There's a v4.0.0 release for PS 0.12 now.
